### ISSUE TITLE
Add description, topics information into about of the repository

### ISSUE THREAD

**Issue by MauNguyenVan** [LubiiiCZ/DevQuickie#1]
I have seen your repository. It is exactly what I am looking for. It is a great project.
You should fill in more descriptions, keys of technology, and topic information into the repository.
This makes other people like me approach easily when searching for your project.
Please do that for other projects to share with more people.

Special thanks for your sharing.

![image](https://github.com/LubiiiCZ/DevQuickie/assets/48544354/ba4fda92-4b59-4417-bf4f-631cde90ca9b)

**Comment by LubiiiCZ** [comment]
Primary objective of this repo is: https://www.youtube.com/@GameDevQuickie
Will try to enhance on this.

**Comment by LubiiiCZ** [comment]
Added.
